wcs:
    resource: "@WCSBundle/Resources/config/routing.yml"
    prefix:   /

test:
    path:      /test/
    defaults:  { _controller: WCSBundle:Thomas:index }

app:
    resource: '@AppBundle/Controller/'
    type: annotation
